### ISSUE TITLE
Build a UI

### ISSUE THREAD

**Issue by LohitakshTrehan** [LohitakshTrehan/ChatRoom#2]
Build a UI as per your liking. You can use any framework. 👍  feel free to ask any doubt to me.

**Comment by tv1ster** [comment]
I will pull some styles for you soon

**Comment by LohitakshTrehan** [comment]
👍 great! @tv1ster

**Comment by tv1ster** [comment]
you can merge it, if you like it

**Comment by LohitakshTrehan** [comment]
@tv1ster  Add your name to contributing.md . generate a pull request again with only contributing.md changed. Your changes are now deployed to heroku app link too 👍
